 theme = "jim_nord_night"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-j = ":buffer-close"
C-k = "vsplit"
C-n = "rotate_view"
C-x = "hsplit"
C-e = "scroll_down"
C-y = "scroll_up"

C-s = ":w"
C-q = ":q"

[keys.insert]
j = { j = "normal_mode", k = "normal_mode" }
k = { j = "normal_mode" }
C-s = ":w"
