theme = "jim_nord"

[editor]
gutters = ["line-numbers", "spacer"]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-indent-retain = 0

[keys.normal]
j = "move_char_left"
k = "move_visual_line_down"
l = "move_visual_line_up"
";" = "move_char_right"
C-d = ":buffer-close"
C-k = "vsplit"
C-x = "hsplit"
C-n = "rotate_view"
C-h = "repeat_last_motion"
C-e = "scroll_down"
C-y = "scroll_up"
C-s = ":w"
C-q = ":q"
C-r = ":reload"
F1 = [":insert-output date +'%H:%M'", "insert_at_line_end"]

[keys.normal.g]
j = "goto_line_start"
";" = "goto_line_end"
[keys.select.g]
j = "goto_line_start"
";" = "goto_line_end"

[keys.normal.space]
l = ":set gutters.layout [\"line-numbers\",\"spacer\"]"
L = ":set gutters.layout []"
o = ":o .panacea/config.ini"

[keys.insert]
j = { j = "normal_mode", k = "normal_mode" }
C-s = ":w"
F1 = [":insert-output date +'%H:%M'", "insert_at_line_end"]

[keys.select]
j = "extend_char_left"
k = "extend_visual_line_down"
l = "extend_visual_line_up"
";" = "extend_char_right"

[keys.normal.C-w]
j = "jump_view_left"
k = "jump_view_down"
l = "jump_view_up"
";" = "jump_view_right"
J = "swap_view_left"
K = "swap_view_down"
L = "swap_view_up"
":" = "swap_view_right"
