[[language]]
name = "go"
formatter = { command = "goimports" }

[[language]]
name = "typescript"
formatter = { command = "eslint", args = ["--max-warnings=0", "--fix"] }
auto-format = true

[[language]]
name = "gdbinit"
scope = "text.gdbinit"
roots = ["text.gdbinit"]
file-types = [".gdbinit"]
comment-token = "#"
