[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "html"
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "css"
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
formatter = { command = "eslint", args = ["--max-warnings=0", "--fix"] }
auto-format = true

[[language]]
name = "go"
formatter = { command = "goimports" }

[[language]]
name = "gdbinit"
scope = "text.gdbinit"
roots = ["text.gdbinit"]
file-types = [".gdbinit", ".lldbinit"]
comment-token = "#"

[[language]]
name = "rust"
