export BASH_SILENCE_DEPRECATION_WARNING=1

if [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
fi
. "$HOME/.cargo/env"

# Added by OrbStack: command-line tools and integration
source ~/.orbstack/shell/init.bash 2>/dev/null || :

# Added by LM Studio CLI tool (lms)
export PATH="$PATH:/Users/jcalabro/.cache/lm-studio/bin"
