#!/usr/bin/env bash

alias ch="gh ChessCom"

alias start_docker="limactl start --name=docker"

export EMSDK="$HOME/go/src/github.com/emscripten-core/emsdk"
export PATH="$EMSDK/upstream/emscripten:$PATH"
export PATH="$EMSDK/node/15.14.0_64bit/bin:$PATH"
export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"

export targetPrimaryAddress="http://localhost:8080"
export targetSecondaryAddress="http://localhost:8080"
export readinessAddress="http://localhost:8080/check"
