#!/usr/bin/env bash

#
# SSH
#
alias j="ssh jlinux"
alias jimvm="ssh jimvm"

#
# Editor
#
export EDITOR="hx"
alias vim="nvim"
alias vi="vim"
alias v="vim"
alias vba="$EDITOR ~/.bash_aliases"
alias vbg="$EDITOR ~/.bash_go"
alias vbw="$EDITOR ~/.bash_work"
alias vbp="$EDITOR ~/.bashrc"
alias vbs="$EDITOR ~/.bash_secrets"
alias vbh="$EDITOR ~/.bash_history"
alias vrc="$EDITOR ~/.vimrc"
alias vrp="$EDITOR ~/.vim_plugins"
alias vkc="$EDITOR ~/.kube/config"
alias vtm="$EDITOR ~/.tmux.conf"
alias vhx="$EDITOR ~/.config/helix/config.toml"
alias va="$EDITOR ~/.config/alacritty/alacritty.yml"
alias vg="$EDITOR ~/.config/ghostty/config"

#
# Git
#
alias s="git status"
alias b="git branch"
alias gpr="git pull -r"
alias gc="git checkout"
alias gcb="git checkout -B"
alias gc-="git checkout --"
alias undo="git reset HEAD^"
alias d="git diff"
alias gl="git log"
alias gs="git stash"
alias am="git add -A; git commit -S -m"
alias gcm="git commit -S -m"
alias amend="git commit --amend -S -m"
alias clean="git clean -fd"
alias update="am 'update' && gp"

function gp {
    git branch --no-color | grep '*' | cut -f 2 -d " " | xargs -L1 git push -u origin
}

function gpsu {
    git branch --no-color | grep '*' | awk '{print $2}' | xargs -L1 git push -u origin
}

#
# ls/exa
#
which exa &> /dev/null
if [ "$?" -eq "0" ]; then
    alias ls="exa -l"
else
    alias ls="ls -lh --color"
fi

alias l="ls"

#
# tmux
#
alias tmux="tmux -2"
alias t="tmux"
alias tm="tmux"
alias tl="tmux ls"
alias tml="tmux l"
alias ta="tmux a"
alias tma="tmux a"
alias a="tmux a"

#
# Grep/ripgrep
#
alias r="rg"

#
# Docker/docker-compose/kubernetes
#
alias dps="docker ps"
alias dl="docker logs"
alias di="docker images"
alias dc="docker-compose"
alias dcd="docker-compose down --volumes"
alias dcu="docker-compose up -d"
alias dbl="dc logs -f db"
alias db=". db/shell.sh"
alias k="kubectl"
alias kx="kubectx"
alias kn="kubens"
alias pods="kubectl get pods"
alias sts="kubectl get sts -o wide"
alias deploy="kubectl get deploy -o wide"
alias token="cat ~/.kube/config | grep token"

function klogs {
    kubectl get pods | rg $1 | head -n 1 | cut -f 1 -d " " | xargs kubectl logs -f
}

#
# Misc
#
alias e="./unix.sh -run"
alias m="make"
alias rmr="rm -r"
alias fail="tail -f"
alias cdt="gh jcalabro/trunk"
alias jai="jai-linux"
alias z="zig"
alias zb="zig build -freference-trace"
alias zr="zig build run -freference-trace"
alias pr="zig build -freference-trace && ./zig-out/bin/panacea"
alias zt="zig build test --summary all -freference-trace"
alias tsu="sudo tailscale up"
alias tsd="sudo tailscale down"
alias tss="tailscale status"

function zig {
    if [ -f '.bin/zig/zig' ]; then
        .bin/zig/zig "$@"
    else
        $LOCAL_BIN_DIR/zig/zig "$@"
    fi
}

function mac_netstat {
    lsof -nP -i4TCP | grep -i listen
}

function adump {
    dwarfdump ./assets/$1/out | less
}
function odump {
    objdump -Sd ./assets/$1/out | less
}
