#!/usr/bin/env bash

alias bs="gh bluesky-social"
alias bi="bs bsky-infra"
function bsh {
  ssh -A root@$1.internal.$2.$BSKY_DOMAIN
}

function ush {
  ssh -A ubuntu@$1
}

#
# Indigo
#

export RELAY_ADMIN_PASSWORD=dummy

#
# Tango
#

alias gta="go test ./atlantis/bsky/server -race -covermode=atomic -v -count=1"
