#!/usr/bin/env bash

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

alias bs="gh bluesky-social"
alias bi="bs bsky-infra"
alias sm="bs seeemore"
alias mydid="echo did:plc:4uz2445cjiw7w4nobfgnu35f"
alias ub="source <(yubi.sh)"

function bsh {
  ssh -A root@$1.internal.$2.$BSKY_DOMAIN
}

function ush {
  ssh -A ubuntu@$1
}

#
# Indigo
#

export RELAY_ADMIN_PASSWORD=dummy

#
# Tango
#

alias gta="go test ./atlantis/bsky/server/... -race -covermode=atomic -v -count=1"

#
# social-app
#

if [ $(uname -s) == "Darwin" ]; then
  export ANDROID_HOME=$HOME/Library/Android/sdk
  export JAVA_HOME="$(brew --prefix openjdk@17)/libexec/openjdk.jdk/Contents/Home"
  export PATH="$JAVA_HOME/bin:$PATH"
fi
