#!/usr/bin/env bash

export GOPRIVATE=github.com/ChessCom/*

export CGH="$GOPATH/src/github.com/ChessCom"

export PATH="$PATH:$HOME/local/bin/clc"

export EMSDK="$HOME/go/src/github.com/emscripten-core/emsdk"
export PATH="$EMSDK/upstream/emscripten:$PATH"
# export PATH="$EMSDK/node/15.14.0_64bit/bin:$PATH"
export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"

alias ch="gh ChessCom"
alias ee="ch explanation-engine"
alias eei="ch explanation-engine-interface"
alias eem="ch explanation-engine-master"

alias plat="ch platform && cd workloads"
alias plat-col="plat && cd chesscom-prod-col-rancher/ceac"
alias plat-gcp="plat && cd chesscom-prod/ceac"
alias plat-us-east5="plat && cd chesscom-prod-us-east5/ceac"
alias plat-staging="plat && cd chesscom-staging/ceac"
alias plat-sandbox="plat && cd chesscom-sandbox/ceac"
alias plat-va="plat && cd chesscom-prod-va-rancher/ceac"

function npm_init {
    npm config set @chesscom:registry https://npm.pkg.github.com
    npm config set '//npm.pkg.github.com/:_authToken' $CHESSCOM_PAT
}

#
# ceac-cluster-proxy
#

export targetPrimaryAddress="http://localhost:8080"
export targetSecondaryAddress="http://localhost:8081"
export readinessAddress="http://localhost:8080/check-best-move"

#
# engine-services
#

export analysisEnginePath="$HOME/local/bin/stockfish"
export useLocalEngines="true"
export numberOfRoutines="12"
export BESTMOVE_BIND_ADDR="localhost"

# hazelcast mc home directory
export MC_HOME="$HOME/.hazelcast/hazelcast-mc"

function hz_offer_bestmove {
    clc queue offer --name best-move-message-queue "$(cat resources/bestmove_request_1.txt)"
}
function hz_offer_bestmove_loop {
    while true; do
        hz_offer_bestmove
    done
}
function hz_clear_bestmove {
    clc queue clear --name best-move-message-queue --yes
}

#
# CEE
#

export CEE_ROOT="$HOME/github.com/ChessCom/explanation-engine"
export PATH="$PATH:$HOME/local/bin/clang14/bin"
export DYLD_LIBRARY_PATH="/opt/homebrew/opt/cairo/lib:$DYLD_LIBRARY_PATH"
export DO_CEE_COMPILE_COMMANDS="true"
export BUILD_SH_SKIP_MAKE="true"

function uci_integration_test {
    cat $1 | jq .uci | rg '"' | sed 's/"//g' | sed 's/,//g' | cut -c 3- | awk '{print}END {print "fetch analysis"}'
}

function cee_go_link_path {
    export LD_LIBRARY_PATH="$1"
    export DYLD_LIBRARY_PATH="$1"
    export CGO_LDFLAGS="-L$1"
}

function cee_go_link_path_dev {
    cee_go_link_path /Users/jcalabro/go/src/github.com/ChessCom/explanation-engine/target/debug/
}
cee_go_link_path_dev

function cee_go_link_path_master {
    cee_go_link_path /Users/jcalabro/go/src/github.com/ChessCom/explanation-engine-master/target/debug/
}

#
# CEE-microservice
#

alias ceem="ch CEE-microservice"
export CEE_BIN="$HOME/local/bin/explanation-engine"
export GAME_STATE_SERVICE_SAVES_PERCENT="1.00"

#
# PGNGen
#

export PGNGEN_SOCKET_PATH="8080"
