#!/usr/bin/env bash

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

export GOPRIVATE="github.com/bluesky-social/*"

alias bs="gh bluesky-social"
alias bi="bs bsky-infra"
alias bi2="bs bsky-infra2"
alias bi3="bs bsky-infra3"
alias bd="bs deploy"
alias bt="bs tango"
alias sm="bs seeemore"
alias mydid="echo -n did:plc:4uz2445cjiw7w4nobfgnu35f"
alias ub="source <(yubi.sh)"

function bsh {
  ssh -A root@$1.internal.$2.$BSKY_DOMAIN "${@:3}"
}

function bbsh {
  ssh -A bsky@$1.internal.$2.$BSKY_DOMAIN "${@:3}"
}

function bush {
  ssh -A ubuntu@$1.internal.$2.$BSKY_DOMAIN "${@:3}"
}

function ush {
  ssh -A ubuntu@$1 "${@:3}"
}

function hex_decode {
  echo
  echo -n $1 | sed 's/0x//' | xxd -r -p
}

#
# Indigo
#

export RELAY_ADMIN_PASSWORD=dummy

#
# Tango
#

alias jta="just test ./atlantis/..."

#
# social-app
#

if [ $(uname -s) == "Darwin" ]; then
  export ANDROID_HOME=$HOME/Library/Android/sdk
  export JAVA_HOME="$(brew --prefix openjdk@17)/libexec/openjdk.jdk/Contents/Home"
  export PATH="$JAVA_HOME/bin:$PATH"
fi
